# Impoting Libraries

In [1]:
import numpy as np
import re
import pandas as pd

# Importing Dataset

In [2]:
data = pd.read_csv('C:/Users/PUSPAK/OneDrive/Desktop/Codes by me/spam_ham_dataset.csv/spam_ham_dataset.csv')

In [3]:
data.head(10)

Unnamed: 0 label                                               text  \
0         605   ham  Subject: enron methanol ; meter # : 988291\r\n...   
1        2349   ham  Subject: hpl nom for january 9 , 2001\r\n( see...   
2        3624   ham  Subject: neon retreat\r\nho ho ho , we ' re ar...   
3        4685  spam  Subject: photoshop , windows , office . cheap ...   
4        2030   ham  Subject: re : indian springs\r\nthis deal is t...   
5        2949   ham  Subject: ehronline web address change\r\nthis ...   
6        2793   ham  Subject: spring savings certificate - take 30 ...   
7        4185  spam  Subject: looking for medication ? we ` re the ...   
8        2641   ham  Subject: noms / actual flow for 2 / 26\r\nwe a...   
9        1870   ham  Subject: nominations for oct . 21 - 23 , 2000\...   

   label_num  
0          0  
1          0  
2          0  
3          1  
4          0  
5          0  
6          0  
7          1  
8          0  
9          0

In [4]:
data.shape

(5171, 4)

In [5]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5171 entries, 0 to 5170
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype 
---  ------      --------------  ----- 
 0   Unnamed: 0  5171 non-null   int64 
 1   label       5171 non-null   object
 2   text        5171 non-null   object
 3   label_num   5171 non-null   int64 
dtypes: int64(2), object(2)
memory usage: 161.7+ KB


- The first column of the dataset doesn't make any sense.
- The 2nd column says **'Spam'** or Not Spam i.e. **'Ham'**, which in turn reflects on 4th column with *0* means **'Ham'** & *1* means **'Spam'**.
- The 3rd column consists of text data

So, I dropped 1st & 2nd columns

In [6]:
data = data.drop(['Unnamed: 0', 'label'], axis = 1)

In [7]:
data.head(10)

text  label_num
0  Subject: enron methanol ; meter # : 988291\r\n...          0
1  Subject: hpl nom for january 9 , 2001\r\n( see...          0
2  Subject: neon retreat\r\nho ho ho , we ' re ar...          0
3  Subject: photoshop , windows , office . cheap ...          1
4  Subject: re : indian springs\r\nthis deal is t...          0
5  Subject: ehronline web address change\r\nthis ...          0
6  Subject: spring savings certificate - take 30 ...          0
7  Subject: looking for medication ? we ` re the ...          1
8  Subject: noms / actual flow for 2 / 26\r\nwe a...          0
9  Subject: nominations for oct . 21 - 23 , 2000\...          0

Checking for the Null Values

In [8]:
data.isnull().sum()  # no null value is there

text         0
label_num    0
dtype: int64

Separating Text data column and label column

In [9]:
X = data['text']
y = data['label_num']

In [12]:
X.head()

0    Subject: enron methanol ; meter # : 988291\r\n...
1    Subject: hpl nom for january 9 , 2001\r\n( see...
2    Subject: neon retreat\r\nho ho ho , we ' re ar...
3    Subject: photoshop , windows , office . cheap ...
4    Subject: re : indian springs\r\nthis deal is t...
Name: text, dtype: object

In [13]:
y.head()

0    0
1    0
2    0
3    1
4    0
Name: label_num, dtype: int64

# Cleaning the text data

In [14]:
from nltk.corpus import stopwords
from nltk.stem.porter import PorterStemmer 
ps = PorterStemmer()

In [15]:
cleaned_data = []
for i in range(0,len(X)):
    mail = re.sub("[^a-zA-z]", " ", X[i]) # substituting any character other than a to z or A to Z
    mail = mail.lower()  # converting all the letters into small case
    mail = mail.split()  # splitting up each of the words from sentences
    # retaing the words if they are not in 'stopwords' as well as stemming all the selected words
    mail = [ps.stem(word) for word in mail if not word in set(stopwords.words('english'))] 
    mail = ' '.join(mail) # again joining those words
    cleaned_data.append(mail)

In [16]:
# replacing the word 'subject' from each of the entry
cleaned = []
for j in range(0,len(cleaned_data)):
    temp = re.sub("subject", " ", cleaned_data[j])
    cleaned.append(temp)

# One Hot Representation & Word Embedding

In [17]:
# Vocabulary size
vocab_size = 4500

In [18]:
from tensorflow.keras.layers import Embedding
from tensorflow.keras.preprocessing.text import one_hot
from tensorflow.keras.preprocessing.sequence import pad_sequences

In [19]:
onehot = [one_hot(k,vocab_size)for k in cleaned] 

In [20]:
onehot

[[328,
  163,
  2001,
  548,
  910,
  2777,
  2002,
  3280,
  4303,
  2800,
  521,
  4052,
  3834,
  2514,
  3530,
  2058,
  4439,
  4478,
  289,
  3004,
  2058,
  2617,
  3506,
  1443,
  3019,
  2654,
  3814,
  1791,
  852,
  3374],
 [4075, 841, 4310, 3780, 276, 1680, 859, 863, 859, 863],
 [1710,
  206,
  2850,
  2850,
  2850,
  1156,
  4115,
  1478,
  207,
  1710,
  2183,
  206,
  1478,
  1588,
  1478,
  207,
  4059,
  3239,
  1941,
  4265,
  165,
  2448,
  2818,
  2984,
  242,
  2448,
  420,
  1781,
  4310,
  4023,
  4265,
  923,
  455,
  1742,
  3397,
  1579,
  1671,
  206,
  1462,
  789,
  4310,
  2250,
  2386,
  1311,
  2924,
  3621,
  2207,
  420,
  242,
  2654,
  4416,
  548,
  789,
  4310,
  3910,
  759,
  3814,
  4265,
  4265,
  4242,
  3102,
  3144,
  870,
  2360,
  1478,
  1962,
  1796,
  870,
  1898,
  2701,
  1671,
  1462,
  896,
  643,
  3144,
  870,
  2262,
  4128,
  238,
  2299,
  2924,
  3472,
  3344,
  2706,
  870,
  2360,
  789,
  3991,
  1588,
  4073,
  2250,
  310

It is an useful tool to make all the sentences (or vectors) of equal size.

In [21]:
# Pad Sequencing
sent_length = 30
emb_data = pad_sequences(onehot, padding = 'pre', maxlen = sent_length)

In [33]:
emb_data

array([[ 328,  163, 2001, ..., 1791,  852, 3374],
       [   0,    0,    0, ...,  863,  859,  863],
       [4490, 2042, 2534, ..., 2991, 2532, 2118],
       ...,
       [2377, 3131, 2654, ..., 1443, 1317, 1278],
       [3280, 1404, 3717, ..., 2294,  521, 2800],
       [1854, 2114, 2137, ..., 1402, 2630,  958]])

# Creating LSTM model

In [22]:
from tensorflow.keras.layers import LSTM
from tensorflow.keras.layers import Dropout
from tensorflow.keras.layers import Dense
from tensorflow.keras.regularizers import l2
from tensorflow.keras.models import Sequential

In [23]:
vec_features = 20
model = Sequential()
model.add(Embedding(vocab_size,vec_features,input_length = sent_length))
model.add(Dropout(0.35))
model.add(LSTM(150, kernel_regularizer=l2(0.01), recurrent_regularizer=l2(0.01), bias_regularizer=l2(0.01)))
model.add(Dropout(0.35))
model.add(Dense(12, activation = 'relu', kernel_regularizer=l2(0.01), bias_regularizer=l2(0.01), activity_regularizer=l2(0.01)))
model.add(Dense(1,activation='sigmoid', kernel_regularizer=l2(0.01), bias_regularizer=l2(0.01), activity_regularizer=l2(0.01)))
model.compile(loss='binary_crossentropy',optimizer='adam',metrics=['accuracy'])
print(model.summary())

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
embedding (Embedding)        (None, 30, 20)            90000     
_________________________________________________________________
dropout (Dropout)            (None, 30, 20)            0         
_________________________________________________________________
lstm (LSTM)                  (None, 150)               102600    
_________________________________________________________________
dropout_1 (Dropout)          (None, 150)               0         
_________________________________________________________________
dense (Dense)                (None, 12)                1812      
_________________________________________________________________
dense_1 (Dense)              (None, 1)                 13        
Total params: 194,425
Trainable params: 194,425
Non-trainable params: 0
__________________________________________________

Creating two numpy arrays for feeding into the LSTM model

In [24]:
X_final = np.array(emb_data)

In [25]:
y_final = np.array(y)

# Splitting the Dataset

In [26]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X_final, y_final, test_size = 0.35, random_state = 0)

In [27]:
X_train, X_test

(array([[3772, 3722,  655, ..., 3609, 3061, 1905],
        [   0,    0,    0, ...,  259, 1739,  983],
        [4439, 2536, 2343, ..., 3267, 1308, 2302],
        ...,
        [3206,  648, 4152, ..., 2316, 4146,  319],
        [3428, 4147,  160, ..., 2037, 1308,  479],
        [2076,  545, 3304, ..., 1308, 1548, 1905]]),
 array([[   0,    0,    0, ..., 1364, 1308,    4],
        [2404, 2046, 4439, ..., 2938, 1443, 3183],
        [3479, 4303, 1988, ..., 1921, 4303, 1863],
        ...,
        [3391,  308, 1087, ..., 3555, 3234,  742],
        [   0,    0,    0, ...,  282, 2553, 1179],
        [ 342, 1816, 3206, ...,  529, 2845, 1309]]))

In [28]:
y_train, y_test

(array([0, 1, 0, ..., 1, 0, 0], dtype=int64),
 array([0, 0, 0, ..., 1, 1, 0], dtype=int64))

In [29]:
# Training the model
model.fit(X_train, y_train, validation_data = (X_test,y_test), epochs = 40, batch_size = 32)

Epoch 1/40
106/106 [==============================] - 4s 40ms/step - loss: 2.4974 - accuracy: 0.7468 - val_loss: 1.6705 - val_accuracy: 0.9193
Epoch 2/40
106/106 [==============================] - 4s 39ms/step - loss: 1.4472 - accuracy: 0.9441 - val_loss: 1.2974 - val_accuracy: 0.9580
Epoch 3/40
106/106 [==============================] - 5s 42ms/step - loss: 1.1785 - accuracy: 0.9625 - val_loss: 1.0639 - val_accuracy: 0.9558
Epoch 4/40
106/106 [==============================] - 5s 48ms/step - loss: 0.9211 - accuracy: 0.9863 - val_loss: 0.8895 - val_accuracy: 0.9530
Epoch 5/40
106/106 [==============================] - 4s 35ms/step - loss: 0.7507 - accuracy: 0.9899 - val_loss: 0.7516 - val_accuracy: 0.9448
Epoch 6/40
106/106 [==============================] - 5s 48ms/step - loss: 0.6188 - accuracy: 0.9923 - val_loss: 0.6291 - val_accuracy: 0.9536
Epoch 7/40
106/106 [==============================] - 3s 32ms/step - loss: 0.5144 - accuracy: 0.9935 - val_loss: 0.5494 - val_accuracy: 0.9519

Predicting the results

In [30]:
y_pred  = model.predict_classes(X_test)

Instructions for updating:
Please use instead:* `np.argmax(model.predict(x), axis=-1)`,   if your model does multi-class classification   (e.g. if it uses a `softmax` last-layer activation).* `(model.predict(x) > 0.5).astype("int32")`,   if your model does binary classification   (e.g. if it uses a `sigmoid` last-layer activation).


# Confusion Matrix

In [31]:
from sklearn.metrics import confusion_matrix 
cm = confusion_matrix(y_test, y_pred)
print(cm)

[[1255   50]
 [  25  480]]


# Accuracy Score

In [32]:
from sklearn.metrics import accuracy_score
acc = accuracy_score(y_test, y_pred)
print(acc*100, "%")

95.85635359116023 %
